= Hardware specifications

Where did your run your tests? A laptop, or goldengate?

Laptop (shh goldengate)

What are the performance specifications of the machine: number and speed of
processors, size of RAM? (use `lscpu` and `free -m`)
 
ssh: 64 CPU's, 1200 MHz. RAM is 83738 mebibyte or 99 gigabytes. 
pc: 8 CPU's, 1991 MHz, RAM is 12389 mebibyte or 12 gigabyte


= Allocations

How many bytes does mylloc_list allocate when the program ends? Explain why.
 
1156 bytes, or 116 + 1040. The first call for memory only allocates 116 bytes,
which is the requested size (100) plus the size of a chunk struct (16). Because the
same size is asked for and then immediatly freed, the same chunk is allocated 
for each call, so the memory allocated after reach interation of the loop is the
same, (1156) after the first call. When that 2nd 100 bytes is asked for, the
linked list is looked through (and the block that was jsut freed is reallocated).

In `simple.c`, where does the increase in 1040 bytes come from?
Why is the value 1040 bytes?

After the first malloc in `reallocate.c`, printf is called which uses memory to
store it's given string. By default it asks for 1040 bytes for this string, and 
in consecutive malloc calls, the number of bytes don't increase beyond 1156,
because the memory allocated for the string get's reused for the next printf 
call.


= Fragementation

What is fragmentation? What is the difference between internal and external 
fragmentation?

Fragmentation occurs when data that could be stored consecutively is separated 
into many different parts of memory in a way that wastes space. Internal 
fragmentation refers to allocating a larger part of memory than is used by the 
data that memory is marked for. Data that could be stored in that extra space 
must be stored somewhere else, using more memory than necessary. External 
fragmentation refers to free blocks of memory that are too small to write data 
to. This data must be written somewhere else, even if cumulatively the freed 
memory blocks are large enough to store the data. This space is wasted if a 
program can't reorganize and/or combine these blocks.
Because the implementation of mylloc didn't split up chunks to make them smaller
and a disproportionate ammount of malloc's are small, the internal fragmentation
seemd to be worse than the external fragmentation (below).

....
The initial top of the heap is 0x7fddcf52b000.
Total blocks: 160 Free: 102 Used: 58
(Internal unused) total: 178682 average: 3080.7 smallest: 511 largest: 3979
(External unused) total: 144325 average: 1415.0 smallest: 6 largest: 3962
0
The current top of the heap is 0x7fddcf583127.
Increased by 352 (0x160) Kbyte
Total blocks: 166 Free: 112 Used: 54
(Internal unused) total: 159454 average: 2952.9 smallest: 107 largest: 3991
(External unused) total: 177529 average: 1585.1 smallest: 6 largest: 3970
1
The current top of the heap is 0x7fddcf588f27.
Increased by 375 (0x177) Kbyte
Total blocks: 168 Free: 116 Used: 52
(Internal unused) total: 157088 average: 3020.9 smallest: 129 largest: 3977
(External unused) total: 189321 average: 1632.1 smallest: 6 largest: 3962
2
The current top of the heap is 0x7fddcf58ae82.
Increased by 383 (0x17f) Kbyte
Total blocks: 171 Free: 119 Used: 52
(Internal unused) total: 160672 average: 3089.8 smallest: 146 largest: 3989
(External unused) total: 201215 average: 1690.9 smallest: 6 largest: 3972
3
The current top of the heap is 0x7fddcf58dd88.
Increased by 395 (0x18b) Kbyte
Total blocks: 174 Free: 124 Used: 50
(Internal unused) total: 145974 average: 2919.5 smallest: 6 largest: 3984
(External unused) total: 222185 average: 1791.8 smallest: 6 largest: 3974
4
The current top of the heap is 0x7fddcf590c95.
Increased by 407 (0x197) Kbyte
Total blocks: 175 Free: 115 Used: 60
(Internal unused) total: 191611 average: 3193.5 smallest: 984 largest: 3986
(External unused) total: 189120 average: 1644.5 smallest: 6 largest: 3972
5
The current top of the heap is 0x7fddcf591c45.
Increased by 411 (0x19b) Kbyte
Total blocks: 175 Free: 127 Used: 48
(Internal unused) total: 153391 average: 3195.6 smallest: 381 largest: 3991
(External unused) total: 227211 average: 1789.1 smallest: 6 largest: 3972
6
The current top of the heap is 0x7fddcf591c45.
Increased by 411 (0x19b) Kbyte
Total blocks: 176 Free: 124 Used: 52
(Internal unused) total: 154837 average: 2977.6 smallest: 138 largest: 3989
(External unused) total: 219923 average: 1773.6 smallest: 6 largest: 3986
7
The current top of the heap is 0x7fddcf592bf5.
Increased by 414 (0x19e) Kbyte
Total blocks: 177 Free: 117 Used: 60
....
